### ISSUE TITLE
Forging

### ISSUE THREAD

**Issue by vnlitvinov** [modin-project/modin#2393]
This is the epic to track moving all packaging activities for `conda` packages to conda-forge, so there would eventually be no need for `-c intel/label/modin` when installing `modin` via `conda`.

Known package groups that we want to move or update in `conda-forge` feedstocks:
- [x] ray
  - [x] colorful (ray dependency)
  - [x] dm-tree (ray dependency)
  - [ ] gpustat on Windows (optional ray dependency)
    - [x] mockito (gpustat testing dependency)
  - [x] gym-atari on Windows (ray-rllib dependency)
    - [x] atari-py on Windows (gym-atari dependency)
  - [x] py-spy on Windows (optional ray-debug dependency)
- [ ] omniscidb (includes dbe4py)
- [ ] modin

**Comment by anmyachev** [comment]
@vnlitvinov do you have a plan to update `ray-core` to `1.1.0` version?

**Comment by anmyachev** [comment]
@vnlitvinov Is there anything left to do here or can the PR be closed?

**Comment by pyrito** [comment]
> @vnlitvinov Is there anything left to do here or can the PR be closed?

bump!
