### ISSUE TITLE
Modin project suggestions

### ISSUE THREAD

**Issue by devin-petersohn** [modin-project/modin#658]
## Modin Potential Projects

The purpose of this issue is to have a single place for all issues good for new users/projects we are working on/etc. It is also intended to give prospective contributors an idea of what would be highest impact to work on. 

### Overview
If you are interested in contributing to Modin, welcome! If you are interested in contributing something that isn't here, let us know and we'll add it! A good place to start looking for issues to contribute to is in the  [Good First Issue 🔰](https://github.com/modin-project/modin/labels/good%20first%20issue%20%3Abeginner%3A) or [Help Wanted 🌐](https://github.com/modin-project/modin/labels/Help%20Wanted%20%3Aglobe_with_meridians%3A) tagged issues.

### Table of Contents
**1.) APIs**
**2.) Experimental Features**
**3.) Query Processing/Planning**
**4.) System Level Enhancements**

#### New APIs
The following APIs are highest priority in Modin (in no particular order). This is based on the number of people requesting it and the number of people using it from our study of usage. If you would like to contribute a particular API, please comment on the related issue:

- [x] `pivot_table`: #1200
- [x] ~`groupby` with list of columns: #75~ Added in #987  
- [x] ~parallel `read_excel`: #467~ Added in #1648
- [ ] parallel `read_pickle`: #529 
- [x] ~~parallel `read_json`: #554~~ Added in #715 
- [x] ~~Compressed `read_csv`: #630~~ Added in #682 
- [x] ~`drop_duplicates`: #634~ Added in #892 
- [x] ~`pd.value_counts`/`Series.value_counts`: #653~ Added in #1535 
- [x] ~~`Series.str`: #654~~ Added in #713 
- [x] ~~`read_fwf`: #752~~ Added in #1448  

#### Improve performance of existing methods
The following APIs need some improvement. These are typically issues requiring deeper knowledge of Modin internals.

- [x] ~~`groupby` performance: #655~~ Added in #659 
- [ ] ` sort_values` performance: #158 
- [ ] `merge`/`join` performance: #656
- [x] ~~`insert` performance: #670~~ Added in #696 

### 2.) Experimental Features
The following features will either augment the pandas API by providing hints to the system or add some new feature that doesn't exist in pandas.

- [ ] `read_sql` parallelism parameter: #455 
- [ ] Progress bar: #629
- [ ] Read multiple files from S3 into the same DataFrame: #700 

### 3.) Query Processing/Planning
More here later...

### 4.) System Level Enhancements
- [x] ~Add Windows support: #657~ Added in #732
- [ ] GPU DataFrame support: #150 
- [ ] Fixed size Cluster support: #583
- [x] ~Ray autoscaler support: #660~ Added in #661 
- [ ] Add Geopandas API: #671

**Comment by devin-petersohn** [comment]
This is a bit outdated, and we have a lot of these implemented.

**Comment by devin-petersohn** [comment]
Closing to start a new thread, thanks to all who contributed!
